[#installation]
= Installation Manual

In order to install Xillio API on your premises, you first have to set up the <<minimal-configuration>>. On top of that,
it is possible to <<configure-additional-features>> to your liking. Once everything is configured, you are ready to
<<deploy-xillio-api>>.

NOTE: In order to be given access Xillio's Docker images, please contact <<support>>.

[#minimal-configuration]
== Minimal Configuration

In order to deploy the Xillio API with minimal configuration, consider the `stack.yml` file below. <<architecture>>
describes what the listed services are used for.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

.stack.yml
[source,yaml,subs="attributes"]
----
include::stack.yml[]
----

Some lines in this stack file need some additional elaboration or configuration.

[cols="2,6"]
|===
| Stack file line | Elaboration

| `proxy.ports`
| All traffic goes through port 80. Port 8080 exposes Traefik's dashboard to overview your proxy. *Note that the
dashboard does not require a login.*

| `proxy.deploy.placements.constraints`
| It is required for Traefik to run on a manager as the proxy is the entry point for all requests, so is the manager
node.

| `engine.image`
| The image of Xillio Engine to use. We recommend to use the latest release which can be found on
https://cloud.docker.com/u/xillio/repository/docker/xillio/xillio-engine.

| `engine.deploy.replicas`
| The number of instances of Xillio Engine you would like to run. Increase this according to the amount of load.
*Must be at least 1.*

| `engine.environment.spring.datasource.username`
| The username of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_USER`.

| `engine.environment.spring.datasource.password`
| The password of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_PASSWORD`.

| `engine.environment.engine.token-signing-key`
| The Xillio Engine works with JWT access tokens which have to be signed by the server. A string has to be provided
which will be used to sign these tokens.  *We highly recommend you to change this value* to a random string with a
length of 50 to 70 characters.

| `engine.environment.xillio-client-id`
| The client ID used in OAuth requests. *We highly recommend you to change this value.*

| `engine.environment.xillio-client-secret`
| The client secret used in OAuth requests. *We highly recommend you to change this value.*

| `postgres.environment.POSTGRES_USER`
| The username to access the PostgreSQL instance with.

| `postgres.environment.POSTGRES_PASSWORD`
| The username to access the PostgreSQL instance with. *We highly recommend you to change this value.*

| `postgres.command`
| We require PostgreSQL to expose more connections than the default in order to limit throttling by the Xillio API on
high loads.

|===

With the stack file configured, you can either <<configure-additional-features>> or <<deploy-xillio-api>>.

[#configure-additional-features]
== Configure Additional Features

As described in <<architecture>>, there are more services which expose additional features. These features are not
present by default and need to be enabled. This requires additional configuration.

=== Reference Documentation

It is possible to also host the reference documentation belonging to the Xillio Engine version used. In order to do so,
append the following section to the `stack.yml` file:

NOTE: Note that the version used in `docs.image` *must* be the same as used in `engine.image`.

.stack.yml
[source,yaml,subs="attributes"]
----
  docs:
    image: xillio/xillio-engine-docs:2.2.16
    deploy:
      labels:
        traefik.port: 80
        traefik.docs.frontend.rule: PathPrefix:/docs
----

The documentation can now be found on the path `/docs`.

=== Content Scripts

In order to also add the feature to use the <<content-script-agent>>, we need a few more services. In order to let
the Xillio Engine communicate with the `scriptagent` service we need to have a message broker service in between.
This is the `rabbit` service. In order to add these two services, append the following section to the `stack.yml` file:

NOTE: Note that the version used in `scriptagent.image` *must* be the same as used in `engine.image`.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

.stack.yml
[source,yaml,subs="attributes"]
----
  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: REPLACE_ME
      RABBITMQ_DEFAULT_PASS: REPLACE_ME
    ports:
    - 15672:15672

  scriptagent:
    image: xillio/xillio-engine-script-agent:2.2.16
    deploy:
      replicas: 3
    environment:
      AMQP_HOST: rabbit
      AMQP_USER: REPLACE_ME
      AMQP_PASS: REPLACE_ME
----

We need to add the RabbitMQ credentials to the Xillio Engine by adding them to `engine.environment`:

.stack.yml
[source,yaml,subs="attributes"]
----
    environment:
      spring.rabbitmq.username: REPLACE_ME
      spring.rabbitmq.password: REPLACE_ME
----

Some lines in this addition to the stack file need some additional elaboration:

[cols="2,6"]
|===
| Stack file line | Elaboration

| rabbit.environment.RABBITMQ_DEFAULT_USER
| must be the same as `scriptagent.environment.AMQP_USER` and `engine.environment.spring.rabbitmq.username`.

| rabbit.environment.RABBITMQ_DEFAULT_PASS
| must be the same as `scriptagent.environment.AMQP_PASS` and `engine.environment.spring.rabbitmq.password`.

| scriptagent.deploy.replicas
| increasing this value will allow more load on this service. *Must be at least 1* for this feature to work.

|===

[#deploy-xillio-api]
== Deploy Xillio API

In order to deploy a stack file, run the following command on the manager node:

[source,bash]
----
$ docker stack deploy xillio --compose-file stack.yml --prune --with-registry-auth
Creating network xillio_default
Creating service xillio_postgres
Creating service xillio_proxy
Creating service xillio_engine
----

It is going to take a few minutes to pull the images and boot all services. To see the status of the deployment you can
execute:

[source,bash]
----
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                         PORTS
vwfmazh43t67        xillio_engine       replicated          2/2                 xillio/xillio-engine:2.2.16
ub4o6wdbqzhm        xillio_postgres     replicated          1/1                 postgres:10.5
pu7zepl225lo        xillio_proxy        replicated          1/1                 traefik:1.6                   *:80->80/tcp, *:8080->8080/tcp

----

Once all services have the desired amount on replicas, Xillio API should be up and running. You can now access the Xillio
API, on the manager, node through `http://127.0.0.1/v2` and `http://127.0.0.1/oauth`. The documentation (if configured)
is hosted on `http://127.0.0.1/docs`. To see Traefik's proxy dashboard you could browse to `http://127.0.0.1:8080`.

In order to verify that the Xillio API is locally accessible you could perform a GET request to
`http://127.0.0.1/v2/system/ping`.

== Troubleshooting

If it takes too long for the services to come online, you can check the state of the stack:

```bash
docker stack ps xillio --no-trunc
```

You may see errors in the output.

=== Error: no suitable node

You may have forgotten to add the `storage` label to one of your nodes. Check out section: <<assign-storage-label>>.

=== Error: task non-zero exit (1)

One of the services may have been misconfigured. Use `docker service logs <service-name>` to find more details about
the problem.

=== Error: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

This might occur due to conflicts with OpenVPN. Stop the OpenVPN service with `service openvpn stop` in order to remove
the conflict.


