[#installation]
= Installation Manual

In order to install Xillio API on your premises, you first have to set up the <<minimal-configuration>>. On top of that,
it is possible to <<configure-additional-features>> to your liking. Once everything is configured, you are ready to
<<deploy-xillio-api>>.

[#minimal-configuration]
== Minimal Configuration

In order to deploy the Xillio API with minimal configuration, consider the `stack.yml` file below. <<architecture>> describes
what the three listed services are used for.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

// TODO: Is configuration of Xillio Client ID & Secret advised? It is still used in the /oauth endpoint... Defaults to xillio/xillio
.stack.yml
[source,yaml,subs="attributes"]
----
include::stack.yml[]
----

Some lines in this stack file need some additional elaboration or configuration.

[cols="2,6"]
|===
| Stack file line | Elaboration

| `proxy.ports`
| All traffic goes through port 80. Port 8080 exposes Traefik's dashboard to overview your proxy. *Note that the dashboard
does not require a login.*

| `proxy.deploy.placements.constraints`
| It is required for Traefik to run on a manager as the proxy is the entry point for all requests, so is the manager node.

| `engine.image`
| The image of Xillio Engine to use. We recommend using the latest release which can be found on
https://api.xill.io/v2/system/version or on https://cloud.docker.com/u/xillio/repository/docker/xillio/xillio-engine.
In order to be given access to these images, please contact <<support>>.

| `engine.deploy.replicas`
| The amount of instances of Xillio Engine you would like to run. Increase this according to the amount of load.
*Must be at least 1.*

| `engine.environment.spring.datasource.username`
| The username of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_USER`.

| `engine.environment.spring.datasource.password`
| The password of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_PASSWORD`.

| `engine.environment.engine.token-signing-key`
| The Xillio Engine works with JWT access tokens which have to be signed by the server. A string has to be provided
which will be used to sign these tokens.  *We highly recommend you to change this value* to a random string with a
length of 50 to 70 characters.

| `engine.environment.engine.single-tenant-mode`
| This boots the Xillio Engine in single tenant mode. We recommend this using this unless you need a multitenancy system.
// TODO: Add reference to additional feature configuration multitenancy.

| `postgres.environment.POSTGRES_USER`
| The username to access the postgres instance with.

| `postgres.environment.POSTGRES_PASSWORD`
| The username to access the postgres instance with. *We highly recommend you to change this value.*

| `postgres.environment.command`
| We require PostgreSQL to expose more connection than default in order to limit throttling by the Xillio API on high loads.

|===

With the stack file configured, you can either <<configure-additional-features>> or <<deploy-xillio-api>>.

[#configure-additional-features]
== Configure Additional Features

As described in <<architecture>>, there are more services which expose additional features. These features are not
present by default and need to be enabled. This requires additional configuration.

=== Documentation

It is possible to also host the reference documentation belong to the Xillio Engine version used. In order to do so,
add the following section to the `stack.yml` file:

NOTE: Note that the version used in `docs.image` should be the same as used in `engine.image`.

.stack.yml
[source,yaml,subs="attributes"]
----
  docs:
    image: xillio/xillio-engine-docs:2.2.16
        deploy:
          labels:
            traefik.port: 80
            traefik.docs.frontend.rule: PathPrefix:/docs
----

The documentation can now be found on the path `/docs`.

// TODO: === Content Scripts

// TODO: === Multitenancy

[#deploy-xillio-api]
== Deploy Xillio API

In order to deploy a stack file, run the following command on the manager node:

[source,bash]
----
$ docker stack deploy xillio --compose-file stack.yml --prune --with-registry-auth
Creating network xillio_default
Creating service xillio_postgres
Creating service xillio_proxy
Creating service xillio_engine
----

It is going to take a few minutes to pull the images and boot all services. To see the status of the deployment you can
execute:

[source,bash]
----
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                         PORTS
vwfmazh43t67        xillio_engine       replicated          2/2                 xillio/xillio-engine:2.2.16
ub4o6wdbqzhm        xillio_postgres     replicated          1/1                 postgres:10.5
pu7zepl225lo        xillio_proxy        replicated          1/1                 traefik:1.6                   *:80->80/tcp, *:8080->8080/tcp

----

// TODO: Explain on retrieval of manager IP and maybe a paragraph about linking a domain to the Xillio API.
// TODO: Transfer the section about testing locally.

Once all services have the desired amount on replicas, Xillio API should be up and running. You can now view the proxy
overview at `http://{{manager-IP}}:8080/`. Browse `http://{{manager-IP}}/v2/system/version` in order to verify whether
Xillio API booted correctly.

== Troubleshooting

If it takes too long for the services to come online, you can check the state of the stack:

```bash
docker stack ps xillio --no-trunc
```

You may see errors in the output.

=== Error: no suitable node

You may have forgotten to add the `storage` label to one of your nodes. Check out section: <<assign-storage-label>>.

=== Error: task non-zero exit (1)

One of the services may have been misconfigured. Use `docker service logs <service-name>` to find more details about
the problem.

=== Error: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

This might occur due to conflicts with OpenVPN. Stop the OpenVPN service with `service openvpn stop` in order to remove
the conflict.


