[#installation]
= Installation Manual

In order to install Xillio API on your premises, you first have to set up the <<minimal-configuration>>. On top of that,
it is possible to <<configure-additional-features>> to your liking. Once everything is configured, you are ready to
<<deploy-xillio-api>>.

NOTE: In order to be given access Xillio's Docker images, please contact <<support>>.

[#minimal-configuration]
== Minimal Configuration

In order to deploy the Xillio API with minimal configuration, consider the `stack.yml` file below. <<architecture>> describes
what the listed services are used for.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

// TODO: Is configuration of Xillio Client ID & Secret advised? It is still used in the /oauth endpoint... Defaults to xillio/xillio
.stack.yml
[source,yaml,subs="attributes"]
----
include::stack.yml[]
----

Some lines in this stack file need some additional elaboration or configuration.

[cols="2,6"]
|===
| Stack file line | Elaboration

| `proxy.ports`
| All traffic goes through port 80. Port 8080 exposes Traefik's dashboard to overview your proxy. *Note that the dashboard
does not require a login.*

| `proxy.deploy.placements.constraints`
| It is required for Traefik to run on a manager as the proxy is the entry point for all requests, so is the manager node.

| `engine.image`
| The image of Xillio Engine to use. We recommend to use the latest release which can be found on
https://api.xill.io/v2/system/version or on https://cloud.docker.com/u/xillio/repository/docker/xillio/xillio-engine.

| `engine.deploy.replicas`
| The number of instances of Xillio Engine you would like to run. Increase this according to the amount of load.
*Must be at least 1.*

| `engine.environment.spring.datasource.username`
| The username of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_USER`.

| `engine.environment.spring.datasource.password`
| The password of the PostgreSQL instance as configured at `postgres.environment.POSTGRES_PASSWORD`.

| `engine.environment.engine.token-signing-key`
| The Xillio Engine works with JWT access tokens which have to be signed by the server. A string has to be provided
which will be used to sign these tokens.  *We highly recommend you to change this value* to a random string with a
length of 50 to 70 characters.

| `engine.environment.engine.single-tenant-mode`
| This deploys the Xillio Engine in single tenant mode. We recommend using this unless you need a <<multitenancy>>
system.

| `postgres.environment.POSTGRES_USER`
| The username to access the PostgreSQL instance with.

| `postgres.environment.POSTGRES_PASSWORD`
| The username to access the PostgreSQL instance with. *We highly recommend you to change this value.*

| `postgres.environment.command`
| We require PostgreSQL to expose more connections than the default in order to limit throttling by the Xillio API on high loads.

|===

With the stack file configured, you can either <<configure-additional-features>> or <<deploy-xillio-api>>.

[#configure-additional-features]
== Configure Additional Features

As described in <<architecture>>, there are more services which expose additional features. These features are not
present by default and need to be enabled. This requires additional configuration.

=== Reference Documentation

It is possible to also host the reference documentation belonging to the Xillio Engine version used. In order to do so,
append the following section to the `stack.yml` file:

NOTE: Note that the version used in `docs.image` *must* be the same as used in `engine.image`.

.stack.yml
[source,yaml,subs="attributes"]
----
  docs:
    image: xillio/xillio-engine-docs:2.2.16
    deploy:
      labels:
        traefik.port: 80
        traefik.docs.frontend.rule: PathPrefix:/docs
----

The documentation can now be found on the path `/docs`.

=== Content Scripts

In order to also add the feature to use the <<content-script-agent>>, we need a few more services. In order to let
the Xillio Engine communicate with the `scriptagent` service we need to have a message broker service in between.
This is the `rabbit` service. In order to add these two services, append the following section to the `stack.yml` file:

NOTE: Note that the version used in `scriptagent.image` *must* be the same as used in `engine.image`.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

.stack.yml
[source,yaml,subs="attributes"]
----
  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: REPLACE_ME
      RABBITMQ_DEFAULT_PASS: REPLACE_ME
    ports:
    - 15672:15672

  scriptagent:
    image: xillio/xillio-engine-script-agent:2.2.16
    deploy:
      replicas: 3
    environment:
      AMQP_HOST: rabbit
      AMQP_USER: REPLACE_ME
      AMQP_PASS: REPLACE_ME
----

Some lines in this stack file need some additional elaboration:

[cols="2,6"]
|===
| Stack file line | Elaboration

| rabbit.environment.RABBITMQ_DEFAULT_USER
| must be the same as `scriptagent.environment.AMQP_USER` and `engine.environment.spring.rabbitmq.username`.

| rabbit.environment.RABBITMQ_DEFAULT_PASS
| must be the same as `scriptagent.environment.AMQP_PASS` and `engine.environment.spring.rabbitmq.password`.

| scriptagent.deploy.replicas
| increasing this value will allow more load on this service. *Must be at least 1* for this feature to work.

|===


We need to add the RabbitMQ credentials to the Xillio Engine by adding them to `engine.environment`:

.stack.yml
[source,yaml,subs="attributes"]
----
    environment:
      spring.rabbitmq.username: REPLACE_ME
      spring.rabbitmq.password: REPLACE_ME
----



[#multitenancy]
=== Multitenancy

In order to use a multitenancy system in the Xillio Engine, additional configuration is required. Append the following
section to the `stack.yml` file:

NOTE: Note that the version used in `admin_server.image` and `admin_portal.image` *must* be the same as used
in `engine.image`.

CAUTION: Copying the `REPLACE_ME` values without changing them is a critical security issue!

.stack.yml
[source,yaml,subs="attributes"]
----
admin_server:
    image: xillio/xillio-admin-portal-server:2.2.16
    deploy:
      labels:
        traefik.port: 4000
        traefik.api.frontend.rule: Host:admin.REPLACE_ME;PathPrefix:/api
    environment:
      XILLIO_API_HOST: *.REPLACE_ME
      XILLIO_API_PUBLIC_URL: http://*.REPLACE_ME
      XILLIO_TOKEN_URL: http://engine:8080/oauth/token
      XILLIO_API_URL: http://engine:8080/v2
      XILLIO_CLIENT_ID: REPLACE_ME
      XILLIO_CLIENT_SECRET: REPLACE_ME
      GITHUB_ORGANIZATION: REPLACE_ME
      GITHUB_CLIENT_ID: REPLACE_ME
      GITHUB_CLIENT_SECRET: REPLACE_ME
      CREATE_TENANT_ROLE: REPLACE_ME
      UPDATE_TENANT_ROLE: REPLACE_ME
      LIST_TENANTS_ROLE: REPLACE_ME
      INSPECT_TENANT_ROLE: REPLACE_ME
      DELETE_TENANT_ROLE: REPLACE_ME

  admin:
    image: xillio/xillio-admin-portal:2.2.16
    deploy:
      labels:
        traefik.port: 80
        traefik.static.frontend.rule: Host:admin.REPLACE_ME;PathPrefix:/static
        traefik.dashboard.frontend.rule: Host:admin.REPLACE_ME
----

[cols="2,6"]
|===
| Stack file line | Elaboration

|admin_server.deploy.labels.traefik.api.frontend.rule
| //TODO explain this all


|===

Furthermore, we need to add the following environment variables to the `engine.environment`. Note that
`engine.environment.engine.single-tenant-mode` is now set to `false`.

.stack.yml
[source,yaml,subs="attributes"]
----
    environment:
      engine.xillio-client-id: REPLACE_ME
      engine.xillio-client-secret: REPLACE_ME
      engine.host: xillio-engine
      engine.single-tenant-mode: "false"
----


[cols="2,6"]
|===
| Stack file line | Elaboration

| environment.engine.xillio-client-id:
| TODO

| environment.engine.xillio-client-secret
| TODO

|===


[#deploy-xillio-api]
== Deploy Xillio API

In order to deploy a stack file, run the following command on the manager node:

[source,bash]
----
$ docker stack deploy xillio --compose-file stack.yml --prune --with-registry-auth
Creating network xillio_default
Creating service xillio_postgres
Creating service xillio_proxy
Creating service xillio_engine
----

It is going to take a few minutes to pull the images and boot all services. To see the status of the deployment you can
execute:

[source,bash]
----
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                         PORTS
vwfmazh43t67        xillio_engine       replicated          2/2                 xillio/xillio-engine:2.2.16
ub4o6wdbqzhm        xillio_postgres     replicated          1/1                 postgres:10.5
pu7zepl225lo        xillio_proxy        replicated          1/1                 traefik:1.6                   *:80->80/tcp, *:8080->8080/tcp

----

// TODO: Explain on retrieval of manager IP and maybe a paragraph about linking a domain to the Xillio API.

Once all services have the desired amount on replicas, Xillio API should be up and running. You can now view the proxy
overview at `http://{{manager-IP}}:8080/`. Browse `http://{{manager-IP}}/v2/system/version` in order to verify whether
Xillio API booted correctly.

== Troubleshooting

If it takes too long for the services to come online, you can check the state of the stack:

```bash
docker stack ps xillio --no-trunc
```

You may see errors in the output.

=== Error: no suitable node

You may have forgotten to add the `storage` label to one of your nodes. Check out section: <<assign-storage-label>>.

=== Error: task non-zero exit (1)

One of the services may have been misconfigured. Use `docker service logs <service-name>` to find more details about
the problem.

=== Error: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

This might occur due to conflicts with OpenVPN. Stop the OpenVPN service with `service openvpn stop` in order to remove
the conflict.


