[[local-testing]]
= Local Testing

Now that the Xillio Engine is successfully deployed, you could start making requests locally in order to verify that
everything works as expected. This step is not necessary, and if everything went right, you can <<getting-started, get started>>
right away.

== Modify the Hosts File

In order to test locally, you have to modify your `hosts` file to map custom host names to the IP address of the machine where the Xillio API is hosted.
This has to be done since the proxy and the Xillio Engine resolve the host name for routing and discovering tenants.
This is not possible when using IP addresses directly and therefore these mappings are required.

Your hosts file entries will differ slightly depending on the machine where you would like to test from.
You could either test from the manager node itself if you have terminal access,
or you could test from any other machine that has access to the network where the manager node is hosted.

=== Hosts File Location

The hosts file location for Unix machines is `/etc/hosts`.
The hosts file location for Windows machines is `%SYSTEM32%\drivers\etc\hosts`.

NOTE: You need administrator permissions to modify the hosts file.

=== Hosts Entries

Each line in the hosts file is an entry, which contains an IP address and a host name.
If you are testing from the manager node directly, you can use `127.0.0.1` as the IP address.
Otherwise you need to use the IP address of the manager node.

If you have the Xillio Admin UI configured you will also need an entry for this host, which is `admin.local`.
As the hosts file does not support wildcard host names, you need to add an entry for every tenant you wish to access.
The hosts file should look like this:

.hosts
```
# Entry for accessing the Xillio API Documentation on http://local/docs
127.0.0.1       local

# Entry for accessing the Xillio API Admin Portal on http://admin.local
127.0.0.1       admin.local

# Entry for accessing the tenant 'tenant' on
# http://tenant.local/v2 and http://tenant.local/oauth
127.0.0.1       tenant.local

# Entries for every other tenant should be added here as well.
```

== Access the Services

You can now access the Xillio API through `http://tenant.local/v2` and `http://tenant.local/oauth`. The Xillio Admin Portal
(if configured) is hosted on on `http://admin.local`, and the documentation (if configured) is hosted on `http://local/docs`.

To see Traefik's proxy dashboard you could browse to `http://local:8080`.

In order to verify that the Xillio API is locally accessible you could perform a GET request to `http://tenant.local/v2/system/ping`.
